SQL> SELECT dbms_metadata.get_ddl('TABLE', table_name) FROM user_tables;

DBMS_METADATA.GET_DDL('TABLE',TABLE_NAME)                                       
--------------------------------------------------------------------------------
                                                                                
  CREATE TABLE "BANK_USER"."BANKS"                                              
   (	"BANK_ID" NUMBER GENERATED BY DEFAULT                                      
                                                                                
                                                                                
  CREATE TABLE "BANK_USER"."REVIEWS"                                            
   (	"REVIEW_ID" NUMBER GENERATED BY DEFA                                       
                                                                                

SQL> spool off
